site_name: Bash Task Master
site_description: 'Bash Task Master Documentation'
site_author: 'hppr.dev'
site_url: 'https://bash-task-master.readthedocs.io'

#copyright: |
#  &copy; Author

docs_dir: docs/


repo_name: hppr-dev/bash-task-master
repo_url: https://github.com/hppr-dev/bash-task-master
edit_uri: https://github.com/hppr-dev/docs-bash-task-master/blob/master/docs

nav:
  - Introduction: index.md
  - Built In Tasks: built_in_tasks.md
  - Task Files: task_files.md
  - State: state.md
  - Modules: modules.md
  - Drivers: drivers.md
  - Repositories: repositories.md

theme:

  name: 'material'
  #custom_dir: 'theme'
  #favicon: 'assets/images/favicon.png'
  palette:
    scheme: 'slate'

    primary: 'light blue'
    accent: 'deep purple'
    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  
  #language: 'en'
  #direction: 'ltr'
  
  features:

  # Announce
  #
  #- announce.dismiss # Adds a "X" button to dismiss a news banner/mark it as read.*
  
  # Header
  #
  - header.autohide # Hide header when user scrolls past a specific point.
  
  # Navigation:
  #
  - navigation.expand      # Expand all collapsable sections.
  #- navigation.instant     # Instant loading pages.
  #- navigation.indexes     # Attach pages directly to Sections. Incompatible with "toc.integrate"
  #- navigation.sections    # Render top sections as groups.
  - navigation.tabs         # Render top sections as tabs at the top.
  #- navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  #- navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  #- navigation.tracking    # Updates the url with highlighted section anchor.
  
  # Search
  #
  #- search.highlight # Search will highlight the searched word(s) on the page.*
  #- search.share     # Adds an option to share a search query link.*
  #- search.suggest   # Search will suggest the likeliest completion for a word.*
  
  # Table of Contents
  #
  - toc.integrate          # Include the TOC sections in the left navugation.
  
  # Code copy 
  - content.code.copy
  
  icon:
    logo: 'material/library'
    repo: 'material/library'
  
#extra_css:
#extra_javascript:

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/hppr-dev/bash-task-master'
  
  # Hide the "Made with Material for MkDocs" text in the footer of the pages by setting
  #generator: true
  
markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  #- pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  #- pymdownx.highlight:
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  - pymdownx.superfences:
  #- pymdownx.tabbed:
  #- pymdownx.tasklist:
  #- pymdownx.tilde:
